# Site settings
title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

kissmyblog:
  media: "img"
  metadata:
    _posts:
      - name: image
        field:
          element: text
          label: Image
          value: ""
      - name: categories
        field:
          label: Categories
          element: select
          placeholder: Select a category
          options:
            - name: Jekyll
              value: jekyll
            - name: Update
              value: update
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Title
          value: ""
      - name: excerpt
        field:
          element: textarea
          label: Excerpt
          value: ""
          remove_if_blank: true
      - name: author
        field:
          element: text
          label: Author
          value: ""
      - name: comments_enabled
        field:
          element: checkbox
          label: Comments Enabled
          value: true
      - name: tags
        field:
          element: text
          label: Tags
          value: ""
